### ISSUE TITLE
Error: "You are already online."

### ISSUE THREAD

**Issue by haiming-wu** [BITNP/bitsrun#45]
Hi,

We have found an issue. Even though the server has logged out of the account for a day, I try to login to my account with ``bitsrun login -u xxx -p xxx''. However, it outputs the following reported error.

```bash
error: E2620: You are already online.
```

Does anyone know how to fix this bug? We would be grateful for any pointers.

**Comment by spencerwooo** [comment]
Is your device (server) registered in the [*dumb terminal wired internet access*](https://zhunru.bit.edu.cn:8087/) system?

**Comment by spencerwooo** [comment]
what we notice:

* if your device is registered in the _dumb terminal wired internet access_ system, its network access status **cannot be** modified through logging in or out
* if your device is logged in, and you register the device as a dumb terminal afterwards, it will remain logged in (i.e., have internet access)

i cannot guarantee my observations are valid or long-standing, but when my device enter this state of *cannot be logged in or logged out*, i usually resolve this by:

1. unregistering the device from the system
2. logging the device in normally
3. then re-registering the device

**Comment by spencerwooo** [comment]
@haiming-wu Any updates?

**Comment by spencerwooo** [comment]
Assuming the problem is resolved. But feel free to reopen for discussion ;)

**Comment by AswarS** [comment]
i got the same error and i cannot find the devices in 10.0.0.55. ...

**Comment by spencerwooo** [comment]
> i got the same error and i cannot find the devices in 10.0.0.55. ...

Please open a new issue in this repo or at [bitsrun-rs](https://github.com/spencerwooo/bitsrun-rs), whichever version you are using.
