### ISSUE TITLE
关于`ac_id=1`的问题

### ISSUE THREAD

**Issue by CPT-KK** [BITNP/bitsrun#48]
用 ac_id=1 登录校园网，可能会出现浏览器输入 10.0.0.55 提示已经在线，但是无法访问校外网络的问题，可能是涉及到学校的双重认证机制，请考虑更新 ac_id 获取的代码

**Comment by YDX-2147483647** [comment]
> 用 ac_id=1 登录校园网

能否再解释一下？

现在的`ac_id=1`似乎是访问 http://10.0.0.55 跳转得到的，并非硬编码。

https://github.com/BITNP/bitsrun/blob/acba3e6ebfefb343591aa0bbacf222f6d082aa7a/src/bitsrun/user.py#L45-L50

我实际看HTTP响应的`Location`，看到的跳转顺序如下。

1. http://10.0.0.55/
2. http://10.0.0.55/index_1.html
3. /srun_portal_pc?ac_id=1&theme=bit

**Comment by spencerwooo** [comment]
> 请考虑更新 ac_id 获取的代码

@CPT-KK Please provide an alternative. 请提供您认为合理的获取方法。

**Comment by CPT-KK** [comment]
学校 ITC 对校园网的接入指南中提到“认证过程中请勿直接输入10.0.0.55的地址”，稍后我提一个PR，安装 ITC 的要求使用 http 访问其他网站（如www.bit.edu.cn）再跳转到 10.0.0.55，这样 ac_id=8，并且可以正常认证上网

**Comment by YDX-2147483647** [comment]
> 学校 ITC 对校园网的接入指南

原来如此！

> 针对于BIT-Web，……有不少师生反映即使弹出登录成功界面依旧无法正常上网的问题。这是由于我校校园网出于安全问题考虑，认证机制涉及到双重认证（准入认证和准出认证），所以在认证过程中请勿直接输入10.0.0.55的地址，正确的认证方法为：首先打开一个http网址（www.bit.edu.cn），系统会自动重定向到校园网用户认证界面，此时按照提示输入账户密码即可完成认证正常上网，下面为示例的两种网址。（后面是HTTP/HTTPS的截图）
>
> ——[无线网接入指南 - 网络信息技术中心 | 北京理工大学](https://itc.bit.edu.cn/fwzn/zxbl/f2c0c8e939ce4e9cace880d5403fe4b5.htm)

**Comment by CPT-KK** [comment]
#49
