### ISSUE TITLE
Setup GitHub Actions

### ISSUE THREAD

**Issue by spencerwooo** [BITNP/bitsrun#5]
- [ ] For auto-publishing to PyPI: `.github/workflows/release.yml`
- [ ] Setting up pre-commit (maybe)
- [ ] Automated checks via pre-commit: `.github/workflows/ci.yml` (maybe)

The PyPI project is currently owned by me ([spencerwoo](https://pypi.org/user/spencerwoo/)). I'd be happy to provide my PyPI auth token to be stored in this repo's environment variable for GitHub Actions to pick-up, or I can transfer the PyPI project to BITNP's account (provided there is one?).

I don't have permissions to setup GitHub Actions, calling for help (cc @phy25 @felinae98 ...)

**Comment by phy25** [comment]
Added you as an admin of the project (the best thing I can do on a phone)
