### ISSUE TITLE
再续`ac_id=1`的问题

### ISSUE THREAD

**Issue by YDX-2147483647** [BITNP/bitsrun#51]
接着 #48 / https://github.com/spencerwooo/bitsrun-rs/issues/11 。（由于这里没开 GitHub Discussions，就直接发 issue 了。）

---

现在 10.0.0.55 的[北理工网络接入认证客户端下载](http://10.0.0.55/download/download_client.html)提供了 [Linux 命令行客户端](http://10.0.0.55/download/Linux_auth_bit.zip)，其中`Linux_auth_bit/auth-setting`把`acid`固定配置成了`1`。

[Linux_auth_bit.zip](https://github.com/user-attachments/files/16837542/Linux_auth_bit.zip)

```toml
host="10.0.0.55"
campus_postfix=""
campus_url=""
acid="1"
```

---

顺便一猜，这个客户端也许与 https://github.com/z4yx/GoAuthing 有关。

```shell
$ ./auth-client --help
NAME:
   auth-client

USAGE:
   auth-client [options]
auth-client [options] auth [options]
auth-client [options] check

VERSION:
   alpha

COMMANDS:
   auth   (default command) Auth via srun4k portal
   check  check your online status

GLOBAL OPTIONS:
   --host value, -h value      (require) Srun4k portal address
   --username value, -u value  (require) Your account name
   --password value, -p value  (require) Your password
   --debug, -d                 Show debug message
   --config value, -c value    Config file path, ~/.auth-setting by default
   --log value                 Path of log file
   --help                      Print the help
   --version, -v               print the version
```

**Comment by spencerwooo** [comment]
不论如何，如果能够避免这样的问题：

> 用 ac_id=1 登录校园网，可能会出现浏览器输入 10.0.0.55 提示已经在线，但是无法访问校外网络的问题

那我们自动获取 ac_id 的过程应该就是 OK 的。（也就是不是非得和官方客户端保持一致，也许官方客户端也有没考虑到的问题。）
